### ISSUE TITLE
establish license

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/fakeiteasy-assets#1]
I was considering remixing one of these assets for a side project. I wanted to see if it was allowed by the license, but could find no license. I am not a lawyer, so am scared and confused.
I think we should explicitly establish a license for the repo.
Of course, then we'd have to pick one.

[Creative Commons Attribution 4.0](http://choosealicense.com/licenses/cc-by-4.0/)?

**Comment by adamralph** [comment]
For [my blog](http://adamralph.com/), I use [Apache for the code](https://github.com/adamralph/adamralph.github.com/blob/master/LICENSE.txt) (which is permissive, and very similar to MIT) and [Creative Commons Attribution 4.0](https://github.com/adamralph/adamralph.github.com/blob/master/_posts/LICENSE.txt) for the content. I'm also no lawyer so I've no idea if this even stands up legally, but it indicates my intentions, i.e. do pretty much whatever you like with the code, but don't plagiarise my content.

**Comment by blairconrad** [comment]
Thanks, @adamralph. I'm filing comment in the "Creative Commons Attribution 4.0 is fine by me" camp, unless you correct me.

**Comment by adamralph** [comment]
Yep, sure. CC attribution 4.0 make sense. I'll get @vanpak to PR that tomorrow, or I will PR it and she'll merge it.
